export const PRODUCT_TYPE = [
  {
    id: 1,
    title: "Gold Products",
    icon: "/icons/products/gold-product-icon.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Gold Product",
    slug: "Gold Products",
  },
  {
    id: 2,
    title: "Diamond Products",
    icon: "/icons/products/diamond-product-icon.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Diamond Products",
  },
  {
    id: 3,
    title: "Gold Coins",
    icon: "/icons/products/gold-coins-icon.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "goldcoins",
  },
  {
    id: 4,
    title: "Solitiare And Stones",
    icon: "/icons/products/solitaire-icon.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Solitairestone",
    slug: "Solitaire",
  },
];
export const RING_SIZER = [
  {
    id: 1,
    title: "NEW REQUEST",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Gold Product",
    slug: "Gold Products",
  },
  {
    id: 2,
    title: "EXISTING",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Diamond Products",
  },
  {
    id: 3,
    title: "ALL DELIVERED",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "goldcoins",
  },
];
export const CUSTOMER_DATA = [
  {
    id: 1,
    img: "/icons/all-products-icon/imageProfile.svg",
    title: "Profile Data",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Profile Data",
    slug: "profileData",
  },
  {
    id: 2,
    img: "/icons/settings/invoice.svg",
    title: "Address",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Address Data",
    slug: "addressData",
  },
  {
    id: 3,
    img: "/icons/all-products-icon/imageWallet.svg",
    title: "Wallet",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Wallet Data",
    slug: "walletData",
  },
  {
    id: 4,
    img: "/icons/all-products-icon/imageWishlist.svg",
    title: "Wishlist",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Wishlist",
    slug: "wishlistData",
  },
  {
    id: 5,
    img: "/icons/all-products-icon/imageCart.svg",
    title: "Added to Cart",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Added To Cart",
    slug: "addedToCart",
  },
  {
    id: 6,
    img: "/icons/dashboard/view-icon.svg",
    title: "Recently Viewed",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Recently Viewed",
    slug: "recentlyViewed",
  },
  {
    id: 7,
    img: "/icons/all-products-icon/imageOrders.svg",
    title: "Orders",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Orders",
    slug: "orders",
  },
  {
    id: 8,
    img: "/icons/all-products-icon/action.svg",
    title: "Size Options",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Size Options",
    slug: "sizeOptions",
  },
];
export const UPDATE_LIST = [
  {
    id: 1,
    title: "META TAGS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Metaa Tags",
  },
  {
    id: 2,
    title: "OCCASIONS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "occasions",
  },
  {
    id: 3,
    title: "STYLES",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "styles",
  },
  {
    id: 4,
    title: "GIFTS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "themes",
  },
  {
    id: 5,
    title: "CURATED BY",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "curatedBy",
  },
  {
    id: 6,
    title: "SOLITIARES AND STONES ",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "solitiaresAndStones",
  },
  {
    id: 7,
    title: "DELIVERY DAYS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "deliveryDays",
  },
];
export const SOLITIARESANDSTONES_LIST = [
  {
    id: 1,
    title: "Solitaires",
    icon: "/icons/products/solitaire-icon.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Solitaire",
  },
  {
    id: 2,
    title: "Stones",
    icon: "/icons/products/solitaire-icon.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Stones",
  },
];
export const DELIVERY_PARTNER = [
  {
    id: 1,
    title: "BLUEDART",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Bluedart",
  },
  {
    id: 2,
    title: "CRITCALOG",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Criticalog",
  },
];
export const MANUFACTURER_ORDER_STATUS = [
  {
    id: 1,
    title: "STORE DETAILS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
  },
  {
    id: 2,
    title: "ORDER MANAGEMENTS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    link: '',
  },
  {
    id: 3,
    title: "BILLINGS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
  },
  {
    id: 4,
    title: "DELIVERY",
    rightArrow: "/icons/products/right-arrow-icon.svg",
  },
  {
    id: 5,
    title: "COMPLETED ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
  },
];
export const REPORT_TYPE = [
  {
    id: 1,
    title: "STORE REPORT",
    icon: "/icons/products/storeReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Store Report",
    slug: "Store Report",
    link: "/report/store-reports"
  },
  {
    id: 2,
    title: "WEBSITE REPORT",
    icon: "/icons/products/websiteReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Website Report",
    link: "/report/website-report"
  },
  {
    id: 3,
    title: "PRODUCT REPORT",
    icon: "/icons/products/productReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Product Report",
    link: "/report/product-reports"
  },
  {
    id: 4,
    title: "PAYMENT REPORT",
    icon: "/icons/products/paymentReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Payment Report",
    slug: "Payment Report",
    link: "/report/payment-reports"
  },
  {
    id: 5,
    title: "ORDERS REPORT",
    icon: "/icons/products/orderReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Orders Report",
    slug: "Orders Report",
    link: "/report/orders-reports"
  },
  {
    id: 6,
    title: "MANUFACTURING REPORT",
    icon: "/icons/products/ManufactureRepo.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Manufacturing Report",
    link: "/report/manufacturing-reports"
  },
  {
    id: 7,
    title: "DELIVERY REPORT",
    icon: "/icons/products/deliveryReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Delivery Report",
    link: "/report/delivery-reports"
  },
  {
    id: 8,
    title: " OVERALL STORES REPORT",
    icon: "/icons/products/overStoreReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Overall Stores Report",
    slug: "Overall Stores Report",
    link: "/report/overall-stores-reports"
  },
];
export const STORE_TYPE = [
  {
    id: 1,
    title: "CUSTOMER REPORTS",
    icon: "/icons/products/customerReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Customer Report",
    slug: "Customer Report",
  },
  {
    id: 2,
    title: "STOCK TRANSFER REPORT",
    icon: "/icons/products/stockTransfer.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Stock Transfer Report",
  },
  {
    id: 3,
    title: "SALES REPORT",
    icon: "/icons/products/salesReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Sales Report",
    link: "/report/sale-reports"
  },
  {
    id: 4,
    title: "INVENTORY REPORT",
    icon: "/icons/products/inventoryReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Payment Report",
    slug: "Payment Report",
  },
  {
    id: 5,
    title: "ORDERS REPORT",
    icon: "/icons/products/orderReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Orders Report",
    slug: "Orders Report",
  },
  {
    id: 6,
    title: "DELIVERY REPORT",
    icon: "/icons/products/deliveryReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Manufacturing Report",
  },
  {
    id: 7,
    title: "VERIFY REPORTS",
    icon: "/icons/products/verifyReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Delivery Report",
  },
  {
    id: 8,
    title: "RETURN REPORTS",
    icon: "/icons/products/returnReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Overall Stores Report",
    slug: "Overall Stores Report",
  },
  {
    id: 9,
    title: "SOLITAIRE REPORTS",
    icon: "/icons/products/solitareReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Solitare Report",
  },
  {
    id: 10,
    title: "TOTAL INWARD INVENTORY REPORT",
    icon: "/icons/products/totalReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Product Report",
  },
  {
    id: 11,
    title: "CREDIT NOTE REPORTS",
    icon: "/icons/products/creditReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Payment Report",
    slug: "Payment Report",
  },
  {
    id: 12,
    title: "STORE PAYMENT REPORTS",
    icon: "/icons/products/storePay.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Orders Report",
    slug: "",
  },
  {
    id: 13,
    title: "INVOICES REPORTS",
    icon: "/icons/products/invoicesReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 14,
    title: "DAILY WALKIN REPORTS",
    icon: "/icons/products/dailyWalkin.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Daily Walkin Report",
  },
  {
    id: 15,
    title: "B2C SALES REPORT",
    icon: "/icons/products/B2CReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 16,
    title: "B2C SALES RETURN REPORT",
    icon: "/icons/products/b2cSales.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 17,
    title: "B2B SALES INVOICE REPORTS ",
    icon: "/icons/products/salesInvoice.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 18,
    title: "FRANCHISE GST REPORT",
    icon: "/icons/products/gstReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
];
export const WEBSITE_REPORT = [
  {
    id: 1,
    title: "RECENTLY VIEWED",
    icon: "/icons/products/storeReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 2,
    title: "ADDED TO CART",
    icon: "/icons/products/cart_report.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Added To Cart",
  },
  {
    id: 3,
    title: "WISHLIST",
    icon: "/icons/products/productReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "Wishlist",
  },
  {
    id: 4,
    title: "CHECKOUT REPORT",
    icon: "/icons/products/checkout.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Payment Report",
    slug: "Checkout Report",
  },
  {
    id: 5,
    title: "RING SIZER REQUEST REPORT",
    icon: "/icons/products/orderReport.svg",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "Orders Report",
    slug: "Ring Sizer Report",
  },
];
export const PRODUCT_REPORT = [
  {
    id: 1,
    title: "MOST VISITED",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 2,
    title: "TRENDING",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 3,
    title: "SPOTLIGHT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 4,
    title: "LEAST VISITED",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 5,
    title: "MOST ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 6,
    title: "MOST ADDED TO CART",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 7,
    title: "MOST WISHLIST",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 8,
    title: "MOST RETURN PRODUCTS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 9,
    title: "REPAIRING PRODUCTS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 10,
    title: "LINK COLLECTION REPORTS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 11,
    title: "UPLOADED PRODUCTS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 12,
    title: "CATEGORY REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 13,
    title: "SUB-CATEGORY REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
];
export const PAYMENT_REPORT = [
  {
    id: 1,
    title: "GIFTCARDS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 2,
    title: "PROMOCODES",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 3,
    title: "DISCOUNTS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 4,
    title: "PAYMENT REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 5,
    title: "ORDERS REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 6,
    title: "AVERAGE PRICE VALUE",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 7,
    title: "TOTAL CASH SALE - CARD - OTHER SALES",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
];
export const ORDERS_REPORT = [
  {
    id: 1,
    title: "NEW ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 2,
    title: "GLS CHANGES REPORT ",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 3,
    title: "RESIZE ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 4,
    title: "RETURN ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 5,
    title: "REFURNISH ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 6,
    title: "DECLINED ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 7,
    title: "ALL COMPLETED ORDERS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
];
export const MANUFACTURING_REPORT = [
  {
    id: 1,
    title: "TOTAL MANUFACTOR",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 2,
    title: "WEBSITE REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 3,
    title: "PRODUCT REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 4,
    title: "PAYMENT REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 5,
    title: "ORDERS REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 6,
    title: "MANUFACTURING REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
];
export const DELIVERY_REPORT = [
  {
    id: 1,
    title: "STORE REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 2,
    title: "WEBSITE REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 3,
    title: "PRODUCT REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 4,
    title: "PAYMENT REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 5,
    title: "ORDERS REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 6,
    title: "MANUFACTURING REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
];
export const OVERALLSTORES_REPORT = [
  {
    id: 1,
    title: "ORDERS REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 2,
    title: "EMPLOYEE REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 3,
    title: "SALES REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 4,
    title: "INVENTORY REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 5,
    title: "DAILY WALKINS",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 6,
    title: "STORE PAYMENT REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 7,
    title: "MANUFACTURING REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
  {
    id: 8,
    title: "CREDIT REPORT",
    rightArrow: "/icons/products/right-arrow-icon.svg",
    component: "",
    slug: "",
  },
];
