export const SEARCH_PRODUCTS = [
  {
    id: 1,
    title: "Search By Inventories",
    editIcon: "/icons/dashboard/scanner_orange.svg",
    editText: "Scan",
    link: "search-by-inventory",
    pageId: "6364f8e5be4e744854a4b7aa",
  },
  {
    id: 2,
    title: "Cart Page",
    viewIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    link: "/cart",
    pageId: "6364f8f1be4e744854a4b7ab",
  },
  {
    id: 2,
    title: "Checkout Page",
    viewIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/checkout",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "6364f8fabe4e744854a4b7ac",
  },
];
export const MANAGE_STORES = [
  {
    id: 1,
    title: "Manage Store",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 2,
    title: "Manage Inventory",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Accept",
  },
  {
    id: 3,
    title: "Manage Order Return Reason",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 4,
    title: "Manage Order Repair Reason",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 5,
    title: "Store Payment Details",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores/store-payment-details",
    pageId: "63fc48ecf276bd85f048acb6",
  },
  {
    id: 8,
    title: "Manage Employee",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 9,
    title: "Verify Stock",
    editIcon: "/icons/dashboard/view-icon.svg",
    editText: "Verify",
  },
];
export const ORDER_DATA = [
  {
    id: 1,
    title: "Manage Orders",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 2,
    title: "Repair Receipts",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 6,
    title: "Gold Mine",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/generate-gold-mine-order",
    pageId: "63fc44b0f276bd85f048ac98",
  },
  {
    id: 8,
    title: "Completed Orders",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Modify",
    link: "/completed-orders",
    pageId: "63fc44e0f276bd85f048ac99",
  },
];
export const RECENT_ACTIVITIY = [
  {
    id: 1,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    pageId: "",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 2,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    pageId: "",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 3,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    plusIcon: "/icons/dashboard/add.svg",
    addText: "Add",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 4,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 5,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 6,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    manageLogistics: "Manage Loigistics",
  },
  // {
  //     id: 7,
  //     title: "C21CC310F - XX -06 -118Y00-00002",
  //     plusIcon: "/icons/dashboard/add.svg",
  //     manageLogistics: "Inventory"
  // }
];
export const MANAGE_INVOICES = [
  // {
  //     id: 13,
  //     title: "PDF",
  //     link: "/printPdf",
  // },
  {
    id: 1,
    title: "New Invoice",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 2,
    title: "Manage Invoices",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 3,
    title: "Manage Credit Note",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 4,
    title: "Rough Slip",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 5,
    title: "On Approval Stock",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 6,
    title: "All Invoices",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
];
export const MANAGE_CUSTOMERS = [
  {
    id: 1,
    title: "Manage Customers",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/customer",
    pageId: "63fc4685f276bd85f048aca3",
  },
  // {
  //     id: 2,
  //     title: "Customer Store Interactions",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Accept",
  //     link: '/dashboard',
  // },
  // {
  //     id: 3,
  //     title: "Quote Address",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard',
  // },
  {
    id: 2,
    title: "All Customers",
    editIcon: "/icons/dashboard/view-icon.svg",
    editText: "View",
    link: "/customer/all-customer",
    pageId: "63fc4699f276bd85f048aca4",
  },
];
export const ACCOUNT_DATA = [
  {
    id: 1,
    title: "Store Ledger",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Generate",
    pageId: "63fc4acbf276bd85f048acc4",

    viewIcon: "/icons/dashboard/view-icon.svg",
    verifyText: "View",
  },
  {
    id: 2,
    title: "Sales",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4acbf276bd85f048acc5",
  },
  {
    id: 3,
    title: "Purchases",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    pageId: "63fc4acbf276bd85f048acc6",
    addText: "Add",
  },
  {
    id: 4,
    title: "Issue Voucher",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4acbf276bd85f048acc7",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 5,
    title: "Sale Voucher ",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4acbf276bd85f048acc8",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
];
export const SETTING_DATA = [
  {
    id: 1,
    title: "Price Changes Section",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
  },
  {
    id: 10,
    title: "Barcode Generation",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
  },
  {
    id: 8,
    title: "All Logs",
  },
];
export const REPORT_DATA = [
  {
    id: 1,
    title: "Sales Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc46d1f276bd85f048aca5",
    editText: "View",
    link: "/report/sales-report",
  },
  // {
  //   id: 7,
  //   title: "Stock Report",
  //   editIcon: "/icons/dashboard/view-icon.svg",
  //   pageId: "63fc46d1f276bd85f048aca5",
  //   editText: "View",
  //   link: "/report/stock-report",
  // },
  {
    id: 2,
    title: "Manage Store Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc46e1f276bd85f048aca6",
    editText: "View",
    link: "/report/manage-store-report",
  },
  {
    id: 3,
    title: "Inventory Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc46f3f276bd85f048aca7",
    editText: "View",
  },
  {
    id: 4,
    title: "Garnet Lanee Request",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc4738f276bd85f048aca8",
    editText: "View",
  },
  {
    id: 5,
    title: "Stock Transaction Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc4755f276bd85f048aca9",
    editText: "View",
  },
  {
    id: 6,
    title: "Stock Trasfer Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc4767f276bd85f048acaa",
    editText: "View",
  },
];
export const ALL_PRODUCT_DATA = [
  {
    id: 1,
    title: "Add Stock / Stock Generation",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 2,
    title: "Manage Category / Sub Categories",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },

  {
    id: 3,
    title: "Solitiare",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
];
export const DASHBOARDAKJWELLERS_TITLE_DATA = [
  {
    title: "",
    icon: "",
  },
];
