const apiEndPoints = {
  userLogin: "/user/pos/login",
  manufacturers: "/manufacturer",
  manufactuterSrno: "/manufacturer/latestid",
  updatemanufacturer: id => `/manufacturer/${id}`,
  updateposmanufacturer: id => `/manufacturer/pos/${id}`,
  designations: "/designation",
  designationssrno: "/designation/latestid",
  catsrno: "/category/latestid",
  csrno: "/collections/latestid",
  occasionsrno: "/occasions/latestid",
  certificatessrno: "/certificates/latestid",
  stylessrno: "/styles/latestid",
  cartssrno: "/carts/latestid",
  themessrno: "/themes/latestid",
  curatedbysrno: "/curatedby/latestid",
  solitairesrno: "/solitaire/latestid",
  stonessrno: "/stones/latestid",
  stocksrno: "/stocks/latestid",
  ordersrno: "/order/latestid",
  productOrdersrno: "/order-products/latestid",
  lotsrno: "/lots/latestid",
  lotpath: "/lots",
  productsrno: "/product/latestid",
  stockDatasrno: "/stocksdata/latestid",
  subcatsrno: "/sub_category_collections/latestid",
  pages: "/pages",
  getCategory: "/category",
  getSubCategory: "/sub_category_collections",
  getInSubCategory: "/subCategory",
  permission: "/permission",
  products: "/product",
  designtype: "/design-type",
  permissionadd: "/permission/add",
  getCalculatePrice: "/productPrice/order",
  updatedesignation: id => `/designation/${id}`,
  getSingleSubcategory: id => `/sub_category_collections/${id}`,
  getSingleSubcategorydetails: id => `/sub_category_collections/details/${id}`,
  getSingleStylesdetails: id => `/styles/details/${id}`,
  categoryByid: id => `/category/${id}`,
  wallet: "/wallet",
  walletById: id => `/wallet/${id}`,
  walletSrno: "/wallet/latestId",
  transactions: "/transactions",
  user: "/user",
  userSrno: "/user/latestSrno",
  getOtp: "/user/requestOtp",
  verifyOtp: "/user/verifyOtp",
  singleUser: id => `/user/${id}`,
  sizeupdate: (id) => `/user/size/${id}`,
  invoice: "/invoice",
  updateInvoice: id => `/invoice/${id}`,
  fetchInvoiceId: `/invoice/latestid`,
  fetchInvoiceById: `/invoice/getByInvoiceId`,
  solitiare: `/solitaire`,
  stone: `/stones`,
  discount: "/discount",
  discountAction: id => `/discount/${id}`,
  getAllfilters: "/filter",
  // updatefilters: id => `/filter/${id}`,
  getProductKeys: "/product/getFields",
  postfilter: "/filters-next",
  getAllfiltersNext: "/filters-next",
  getFilterById: (id) => `/filters-next/${id}`,
  updatefilters: (id) => `/filters-next/${id}`,
  postSubFilter: "/sub-filters-next",
  getSubFilterById: (id) => `/sub-filters-next/fetch/${id}`,
  updateSubFilter: (id) => `/sub-filters-next/${id}`,
  getAllSubfiltersNext: `/sub-filters-next`,
  updateSolitaire: (id) => `/solitaire/${id}`,
  subFilterData: "/filter/list",
  subFilter: `/subFilter`,
  subFilterById: (id) => `/subFilter/${id}`,
  updateFilterList: id => `/filter/list/${id}`,
  getCustomerReview: "/customer_review",
  updateCxReview: id => `/customer_review/${id}`,
  saveSubCategoryExcel: `/sub_category_collections/upload`,
  postCxReview: `/customer_review`,
  updateStartFrom: `/category/update_start_from`,
  singleBannerCategory: id => `/category/${id}`,
  updateBannerCategory: id => `/category/${id}`,
  imageUpload: "/imageUpload",
  zipUrl: "/zip-url",
  VideoUpload: "/videoUpload",
  collections: "/collections",
  updateCollection: id => `/collections/${id}`,
  saveCollectionExcel: `/collections/upload`,
  getCollections: `/collections`,
  barcodelog: `/generate_barcode`,
  barcodeloglatestId: `/generate_barcode/latestId`,
  occasions: "/occasions",
  updateOccasions: id => `/occasions/${id}`,
  saveOccasionsExcel: `/occasions/upload`,
  certificates: "/certificates",
  updateCertificates: id => `/certificates/${id}`,
  saveCertificatesExcel: `/certificates/`,

  updateSolitiares: id => `/solitaire/${id}`,
  SolitiaresExcel: `/solitaire`,
  updateStones: id => `/stones/${id}`,
  StonesExcel: `/stones`,
  styles: "/styles",
  carts: "/carts",
  updateStyles: id => `/styles/${id}`,
  updateCarts: id => `/carts/${id}`,
  saveStylesExcel: `/styles/upload`,
  saveCartsExcel: `/styles/upload`,
  themes: '/themes',
  updateThemes: (id) => `/themes/${id}`,
  stocks: '/stocks',
  orderProducts: '/order-products',
  stockProductCount: '/stocks/productcount',
  stocksSearch: '/stocks/search-stock',
  stocksSearchAll: '/stocks/search-stock-all',
  updateStocks: (id) => `/stocks/${id}`,
  stocksData: '/stocksdata',
  updateStocksData: (id) => `/stocksdata/${id}`,
  saveThemesExcel: `/themes/upload`,
  curatedby: "/curatedby",
  updateCuratedby: id => `/curatedby/${id}`,
  saveCuratedbyExcel: `/curatedby/upload`,
  subCategoryExcel: `/excel`,
  GlSize: `/glsize`,
  uploadpos: "/upload/pos/addproduct",
  updatesrnopos: "/upload/pos/updatesrno",
  uploadgls: "/upload/pos/addgls",
  uploadglsUpdate: "/upload/pos/updategls",
  uploadsolgls: "/upload/pos/addsolgls",
  uploadposedit: "/upload/pos/updateproduct",
  uploadproductzip: "/zip-productgl",
  latesid: `/glsize/latestid`,
  latesdiscountid: `/discount/latestid`,
  glfilter: "/glfilter",
  priceChange: `/priceChange`,
  makingPrice: `/priceChange/makingPrice`,
  singleProduct: id => `/product/${id}`,
  singleproductByPid: pid => `/product/singleproductByPid/${pid}`,
  singleproductByGl: pid => `/product/singleproductByGl/${pid}`,
  cartData: (id, sid) => `/cartdata/${id}/${sid}`,
  cartDatas: `/cartdata`,
  updatePriceChange: id => `/priceChange/${id}`,
  generatePickUp: `/generate_pickup`,
  latestGpId: `/generate_pickup/latestid`,
  exportPriceQuatation: `/export-price`,
  send: `/export-price/sendMsg`,
  manageStore: `/manage-store`,
  modifyStore: id => `/manage-store/${id}`,
  userStore: id => `/manage-store/user/${id}`,
  storeLatestId: `/manage-store/promo/latestid`,
  storeEmployee: `/store-employee`,
  storeEmpLatestid: `/store-employee/latestid`,
  employeeById: id => `/store-employee/${id}`,
  employee: id => `/store-employee/details/${id}`,
  order: `/order`,
  productOrder: `/order-products`,
  ordersidebar: `/ordersidebar`,
  promocode: `/promocode`,
  modifyPromocode: id => `/promocode/${id}`,
  promoLatestId: `/promocode/promo/latestid`,
  send: `/export-price/sendMsg`,
  storeForInvoice: "/manage-store",
  ringSize: `/notSureRingSize`,
  updataRinRequest: id => `/notSureRingSize/${id}`,
  getRingReqById: id => `/notSureRingSize/ringsize/${id}`,
  generatePickUp: `/generate_pickup`,
  pincode: "shipping_pincode",
  track: `track_order`,
  usertoken: "/token",
  checkCoupon: coupon => `promocode/checkCoupon/${coupon}`,
  resetPass: `/reset-password/user`,
  resetPassById: id => `/reset-password/user/${id}`,
  adminById: id => `/admin/${id}`,
  getAdmin: `/admin`,
  customer: `/user/pos/customer`,
  checkPassword: id => `/admin/checkPassword/${id}`,
  returnReason: `/return-reason`,
  modifyReturnReason: (id) => `/return-reason/${id}`,
  returnSrNo: `/return-reason/returnReasonLatestId`,
  repairReason: `/repair-reason`,
  modifyRepairReason: (id) => `/return-reason/${id}`,
  repairSrNo: `/return-reason/returnReasonLatestId`,
  dailyWalkin: `/manage-store/customer/dailyWalkins`,
  createMsgGroup: `/firebase/groupsMsg`,
  msggroup: (id) => `/firebase/groupsMsg/${id}`,
  message: (id) => `/firebase/messaging/${id}`,
  getChats: (id) => `/firebase/messaging/chats/${id}`,
  firebaseCart: (id) => `/firebase/cart/${id}`,
  firebaseWishlist: (id) => `/firebase/wishlist/${id}`,
  search: `/search/user`,
  checkoutPost:`/checkout`,
  checkout:(id)=>`/checkout/${id}`,
  updateOrderStatus:(id)=>`/order-products/updateOrderStatus/${id}`,
  assignManufacturer:(id)=>`/order-products/updateAssignManufacturer/${id}`,
  requestManufacturer:(id)=>`/order-products/requestStatusManufacturer/${id}`,
  delayedMsg:`/order-products/delyedMsg`,
  markGlsGenerated:(id)=>`/order-products/markGlsGenerated/${id}`,
  // checkoutDel:(id)=>`/checkout/deleteItem/${id}`,
  getCheckoutItem: (id) => `/checkout/checkoutData/${id}`,
  sendWhatsAppMsg: `/checkout/sendWhatsApp`,
  cartStock: `/cartdata/getAllCartStock`,
  userAddress: (id) => `/user/address/${id}`,
  repairReceipt: `/repairReceipt`,
  repairReceiptSrno: "/repairReceipt/latestid",
  fetchRepairReceiptbyInvoice: `/repairReceipt/fetchRepairReceiptbyInvoice`,
  banner: `/banner`,
  bannerById: (id) => `/banner/${id}`,
  subCategoryById: (id) => `/subCategory/${id}`,

  exclusive: `/exclusive`,
  exclusiveById: (id) => `/exclusive/${id}`,

  shuffleProduct: `/product/shuffle/update`,
  shuffleProductOnOff: `/setting/shuffle_on_off/put`,
  shuffleProductGet: `/setting/shuffle_on_off/get`,

  megamenu: `/megamenu`,
  megamenuById: (id) => `/megamenu/${id}`,
  subMegaMenu: (id) => `/megamenu/subtitle/${id}`,
  sub2menu: `/megamenu/sub_menu`,
  sub2menuByid:(id)=>`/megamenu/sub_menu/${id}`,
  sub3menu: `/megamenu/sub_title`,
  sub3menuById: (id) => `megamenu/sub_title/${id}`,
  payByLink: `/payByLink`,
  payByLinkById: (id) => `/payByLink/${id}`,

  meta: `/meta`,
  footer: `/footer`,
  updateFooter: (id) => `/footer/${id}`,
  termsAndConditions: `/termsAndConditions`,
  socialMedia: `/socialMedia`,
  shopByGender: `/shopByGender`,
  shopByGenderId: (id) => `/shopByGender/${id}`,
  expressDeliveryBanner: `/expressDelivery`,
  expressDeliveryBannerId:(id) => `/expressDelivery/${id}`,
  homeVideo:`/setting/homeVideo/put`,
  homeVideoGet:`/setting/homeVideo/get`,
  offers:`/offers`,
  updateOffers: (id) => `/offers/${id}`,
  updateOffersStatus: (id) => `/offers/updateOffersStatus/${id}`
};

export default apiEndPoints;
