export const SEARCH_PRODUCT = [
  {
    id: 1,
    title: "Search By Inventories",
    editIcon: "/icons/dashboard/scanner_orange.svg",
    editText: "Scan",
    link: "/search-by-inventory",
    pageId: "6364f8e5be4e744854a4b7aa",
  },
  {
    id: 2,
    title: "Cart Page",
    viewIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    link: "/cart",
    pageId: "6364f8f1be4e744854a4b7ab",
  },
  {
    id: 3,
    title: "Checkout Page",
    viewIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/checkout",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "6364f8fabe4e744854a4b7ac",
  },
];
export const MANAGE_STORE = [
  {
    id: 1,
    title: "Manage Store",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores",
    pageId: "6364b7debe4e744854a4b7a5",
  },
  {
    id: 2,
    title: "Manage Inventory",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Accept",
    // link: '/manage-inventory',
    link: "/stores/manage-inventory",
    pageId: "63fc48ecf276bd85f048acb2",
  },
  {
    id: 3,
    title: "Manage Store Daily Walkins",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores/daily-walkins",
    pageId: "63fc48ecf276bd85f048acb3",
  },
  {
    id: 4,
    title: "Manage Order Return Reason",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores/return-reason",
    pageId: "63fc48ecf276bd85f048acb4",
  },
  {
    id: 5,
    title: "Manage Order Repair Reason",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores/repair-reason",
    pageId: "63fc48ecf276bd85f048acb5",
  },
  {
    id: 6,
    title: "Store Payment Details",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores/store-payment-details",
    pageId: "63fc48ecf276bd85f048acb6",
  },
  {
    id: 7,
    title: "Manage Stock Transfer",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores/stock-transfer",
    pageId: "63fc48ecf276bd85f048acb7",
  },
  {
    id: 8,
    title: "Inward Stock",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Accept",
  },
  {
    id: 8,
    title: "Manage Employee",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/stores/manage-employee",
    pageId: "63fc48ecf276bd85f048acb8",
  },
  {
    id: 9,
    title: "Verify Stock",
    editIcon: "/icons/dashboard/view-icon.svg",
    editText: "Verify",
    link: "/stores/verify-stock",
    pageId: "63fc48ecf276bd85f048acb9",
  },
  // {
  //     id: 10,
  //     title: "Manage Store User Mapping",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard',
  // },
  // {
  //     id: 11,
  //     title: "Generate New Request",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard',
  // },
];
export const ORDERS_DATA = [
  {
    id: 1,
    title: "Manage Orders",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/new-order",
    // link: "/manage-orders",
    pageId: "63fc433cf276bd85f048ac94",
  },
  {
    id: 2,
    title: "Repair Receipts",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/repair-receipts",
    pageId: "63fc4381f276bd85f048ac95",
  },
  // {
  //   id: 3,
  //   title: "Orders Dispersal",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   link: "/orders-dispersal",
  //   pageId: "63fc448cf276bd85f048ac96",
  // },
  {
    id: 3,
    title: "LTE / Buy Back",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/buy-back",
  },
  {
    id: 4,
    title: "Declined Orders",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/declined-order",
    pageId: "63fc4512f276bd85f048ac9c",
  },
  // {
  //   id: 4,
  //   title: "Orders Received After Manufacturing",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   link: "/received-after-manufacturing",
  //   pageId: "63fc44a1f276bd85f048ac97",
  // },
  {
    id: 6,
    title: "Gold Mine",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/generate-gold-mine-order",
    pageId: "63fc44b0f276bd85f048ac98",
  },
  {
    id: 7,
    title: "Order Management",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 8,
    title: "Completed Orders",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Modify",
    link: "/completed-orders",
    pageId: "63fc44e0f276bd85f048ac99",
  },
  // {
  //   id: 8,
  //   title: "New Order",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   link: "/new-order",
  //   pageId: "63fc44f3f276bd85f048ac9a",
  // },
  // {
  //   id: 9,
  //   title: "Repair Orders",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   link: "/repair-order",
  //   pageId: "63fc44fff276bd85f048ac9b",
  // },
  // {
  //   id: 11,
  //   title: "All Orders",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Modify",
  //   link: "/all-orders",
  //   pageId: "63fc4521f276bd85f048ac9d",
  // },
];
export const RECENT_ACTIVITIES = [
  {
    id: 1,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    pageId: "",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 2,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    pageId: "",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 3,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    plusIcon: "/icons/dashboard/add.svg",
    addText: "Add",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 4,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 5,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    manageLogistics: "Manage Loigistics",
  },
  {
    id: 6,
    title: "Blue Dart",
    plusIcon: "/icons/dashboard/add.svg",
    manageLogistics: "Manage Loigistics",
  },
  // {
  //     id: 7,
  //     title: "C21CC310F - XX -06 -118Y00-00002",
  //     plusIcon: "/icons/dashboard/add.svg",
  //     manageLogistics: "Inventory"
  // }
];
export const MANAGE_INVOICE = [
  // {
  //     id: 13,
  //     title: "PDF",
  //     link: "/printPdf",
  // },
  {
    id: 1,
    title: "New Invoices",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 2,
    title: "Manage Invoices",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/manage-invoices",
    pageId: "63fc456ff276bd85f048ac9e",
  },
  {
    id: 3,
    title: "Manage Credit Note",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/manage-credit-note",
    pageId: "63fc45a0f276bd85f048ac9f",
  },
  {
    id: 4,
    title: "Manage Cash Deposit Challans",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/manage-cash-deposit",
    pageId: "63fc461cf276bd85f048aca0",
  },
  // {
  //     id: 4,
  //     title: "Export Price Data",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Accept",
  //     link:"/export-price-data",
  // },
  // {
  //     id: 5,
  //     title: "Product Details Fetched",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Accept",
  //     link: "/product-details-fetched",
  // },
  // {
  //     id: 6,
  //     title: "Manage Invoice Report",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add"
  // },
  // {
  //     id: 5,
  //     title: "All Invoices",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add"
  // },
  // {
  //     id: 6,
  //     title: "Export Price Data",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: "/export-price-data",
  // },
  // {
  //     id: 7,
  //     title: "Manage Without Discount Invoice",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: "/product-details-fetched",
  // },
  // {
  //     id: 8,
  //     title: "Manage B2b Cash Challans",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add"
  // },
  // {
  //     id: 9,
  //     title: "Manage lnvoice Format",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add"
  // },
  // {
  //     id: 10,
  //     title: "Manage Internal Invoice",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add"
  // },
  {
    id: 5,
    title: "Export Price Quatation",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Accept",
    link: "/export-price-data",
    pageId: "63fc4639f276bd85f048aca1",
  },
  {
    id: 6,
    title: "All Invoices",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    pageId: "63fc464bf276bd85f048aca2",
    addText: "Add",
  },
];
export const MANAGE_CUSTOMER = [
  {
    id: 1,
    title: "Manage Customers",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/customer",
    pageId: "63fc4685f276bd85f048aca3",
  },
  // {
  //     id: 2,
  //     title: "Customer Store Interactions",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Accept",
  //     link: '/dashboard',
  // },
  // {
  //     id: 3,
  //     title: "Quote Address",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard',
  // },
  {
    id: 2,
    title: "All Customers",
    editIcon: "/icons/dashboard/view-icon.svg",
    editText: "View",
    link: "/customer/all-customer",
    pageId: "63fc4699f276bd85f048aca4",
  },
];
export const DELIVERIES_DATA = [
  {
    id: 1,
    title: "Generate Pickup",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Add",
    pageId: "63fc49f9f276bd85f048acba",
    link: "/generate-pickup",
  },
  {
    id: 2,
    title: "Delivery Partner Track Order",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    viewIcon: "/icons/dashboard/view-icon.svg",
    verifyText: "View",
    link: "/delivery-partner-order",
    pageId: "63fc49f9f276bd85f048acbb",
  },
  {
    id: 3,
    title: "Cancel Pickup",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    pageId: "63fc49f9f276bd85f048acbc",
    addText: "Add",
  },
  {
    id: 4,
    title: "Track Order",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    pageId: "63fc49f9f276bd85f048acbd",
    addText: "Add",
  },
  {
    id: 5,
    title: "Check Delivery Days",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc49f9f276bd85f048acbe",
    link: "/check-delivery-days",
  },
  {
    id: 6,
    title: "Completed Deliveries",
    editIcon: "/icons/dashboard/view-icon.svg",
    editText: "View",
    pageId: "63fc49f9f276bd85f048acbf",
  },
  // {
  //     id: 7,
  //     title: "Product Delivery Section",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add"
  // },
];
export const MANUFACTER_DATA = [
  {
    id: 1,
    title: "Manage Manufacture",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4a72f276bd85f048acc0",
    link: "/manufacturer",
  },
  {
    id: 2,
    title: "Manufacturer Management",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4a72f276bd85f048acc1",
    link: "/manufacturer-order-status",
  },
  {
    id: 3,
    title: "Track Orders",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Accept",
    //   link: '/dashboard'
  },
  {
    id: 4,
    title: "Completed Orders",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    link: "/dashboard",
  },
  // {
  //     id: 5,
  //     title: "Stock Statement",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard'
  // },
  // {
  //   id: 6,
  //   title: "All Deliveries",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   pageId: "63fc4a72f276bd85f048acc2",
  //   link: "/all-deliveries",
  // },
  // {
  //   id: 7,
  //   title: "Repairing Item",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   pageId: "63fc4a72f276bd85f048acc3",
  //   link: "/repairing-items",
  // },
];
export const ACCOUNTS_DATA = [
  {
    id: 1,
    title: "Store Ledger",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Generate",
    pageId: "63fc4acbf276bd85f048acc4",
    viewIcon: "/icons/dashboard/view-icon.svg",
    verifyText: "View",
  },
  {
    id: 2,
    title: "Sales",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4acbf276bd85f048acc5",
  },
  {
    id: 3,
    title: "Purchases",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    pageId: "63fc4acbf276bd85f048acc6",
    addText: "Add",
  },
  {
    id: 4,
    title: "Issue Voucher",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4acbf276bd85f048acc7",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
  {
    id: 5,
    title: "Sale Voucher ",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4acbf276bd85f048acc8",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
  },
];
export const SETTINGS_DATA = [
  {
    id: 1,
    title: "Price Changes Section",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4e0df276bd85f048acc9",
    link: "/price-change-section",
  },
  {
    id: 2,
    title: "Promo-Codes",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4e0df276bd85f048acca",
    link: "/promo-code",
  },
  {
    id: 3,
    title: "Discount Section",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4e0df276bd85f048accb",
    link: "/discount",
  },
  {
    id: 4,
    title: "Pannel Access Permission",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4e0df276bd85f048accc",
    link: "/settings/access-and-permission",
  },
  // {
  //     id: 5,
  //     title: "All Logs",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     link: '/dashboard'
  // },
  {
    id: 6,
    title: "Gift Cards",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    //   link: '/dashboard'
  },
  {
    id: 5,
    title: "Garnet Digital Wallet",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc4e0df276bd85f048accd",
    link: "/wallets",
  },
  // {
  //     id: 8,
  //     title: "Manage Invoice Format",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard'
  // },
  // {
  //     id: 9,
  //     title: "GL Tag Creation",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard'
  // },
  {
    id: 10,
    title: "Barcode Generation",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/dashboard",
  },
  {
    id: 11,
    title: "Departments",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/dashboard",
  },
  {
    id: 11,
    title: "Manage Verify Report",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    link: "/dashboard",
  },

  // {
  //   id: "Ashish",
  //   title: "Mega Menu",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   link: "/settings/website-setting/mega-menu",
  // },
  // {
  //   id: "Ashish",
  //   title: "Filter",
  //   editIcon: "/icons/dashboard/edit.svg",
  //   editText: "Edit",
  //   addIcon: "/icons/dashboard/add-icon.svg",
  //   addText: "Add",
  //   link: "/settings/website-setting/filters",
  // },
  
  {
    id: 6,
    title: "Website Settings",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    link: "/settings/website-setting"
  },
  {
    id: 6,
    title: "Manage Certification",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4e0df276bd85f048acce",
    link: "/manageCertification",
  },
  {
    id: 7,
    title: "Ring Sizer",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4e0df276bd85f048accf",
    link: "/ring-sizer",
  },
  {
    id: 8,
    title: "All Logs",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    pageId: "63fc4e0df276bd85f048acd0",
    link: "/logs",
  },
  {
    id: 9,
    title: "Reset Password / Access",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    link: "/reset-password",
  },
];
export const REPORTS_DATA = [
  {
    id: 1,
    title: "Sales Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc46d1f276bd85f048aca5",
    editText: "View",
    link: "/report/sales-report",
  },
  // {
  //   id: 7,
  //   title: "Stock Report",
  //   editIcon: "/icons/dashboard/view-icon.svg",
  //   pageId: "63fc46d1f276bd85f048aca5",
  //   editText: "View",
  //   link: "/report/stock-report",
  // },
  {
    id: 2,
    title: "Manage Store Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc46e1f276bd85f048aca6",
    editText: "View",
    link: "/report/manage-store-report",
  },
  {
    id: 3,
    title: "Inventory Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc46f3f276bd85f048aca7",
    editText: "View",
  },
  {
    id: 4,
    title: "Garnet Lanee Request",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc4738f276bd85f048aca8",
    editText: "View",
  },
  {
    id: 5,
    title: "Stock Transaction Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc4755f276bd85f048aca9",
    editText: "View",
    link: "/report/stock-transation-report",
  },
  {
    id: 6,
    title: "Stock Trasfer Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc4767f276bd85f048acaa",
    editText: "View",
  },
  {
    id: 8,
    title: "Store Sales Report",
    editIcon: "/icons/dashboard/view-icon.svg",
    pageId: "63fc46d1f276bd85f048aca5",
    editText: "View",
    link: "/report/store-sales-report",
  },
];
export const ALL_PRODUCTS_DATA = [
  {
    id: 1,
    title: "Manage Products",
    editIcon: "/icons/dashboard/view-icon.svg",
    addText: "Add",
    addIcon: "/icons/dashboard/add-icon.svg",
    editText: "View",
    pageId: "63fc4794f276bd85f048acab",
    link: "/products",
  },
  {
    id: 2,
    title: "Manage Category / Sub Categories",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc47a8f276bd85f048acac",
    link: "/category",
  },
  {
    id: 3,
    title: "Update Product Data",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc47bdf276bd85f048acad",
    link: "/update-product-data",
  },
  // {
  //     id: 3,
  //     title: "Manage Sub-Category",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/sub-category'
  // },
  {
    id: 4,
    title: "Manage GL Sizes",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc47fef276bd85f048acae",
    link: "/gl-size",
  },
  // {
  //     id: 5,
  //     title: "Stone Stock",
  //     editIcon: "/icons/dashboard/edit.svg",
  //     editText: "Edit",
  //     addIcon: "/icons/dashboard/add-icon.svg",
  //     addText: "Add",
  //     link: '/dashboard'
  // },
  {
    id: 5,
    title: "Link Collection",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc47fef276bd85f048acaf",
    link: "/collection",
  },
  {
    id: 6,
    title: "Solitiare And Stones",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    //   link: '/dashboard'
  },
  {
    id: 7,
    title: "Add Stock / GLS Generation",
    editIcon: "/icons/dashboard/edit.svg",
    editText: "Edit",
    addIcon: "/icons/dashboard/add-icon.svg",
    addText: "Add",
    pageId: "63fc483df276bd85f048acb0",
    link: "/products/add-stock",
  },
];
export const DASHBOARD_TITLE_DATA = [
  {
    title: "",
    icon: "",
  },
];
