import Image from "next/image";
import React, { useState } from "react";
import { Col, Container, Form, Row, Table } from "react-bootstrap";
import Button from "../../../../components/basic/button";
import GradientBtn from "../../../../components/basic/button/gradientButton";
import Text from "../../../../components/basic/text";
import { colors } from "../../../../constants/colors";
import NewProgressBar from "../../../components/progressBar";
import TitleHeader from "../../../components/titleHeader";
import { profileIcon } from "../../../home/searchProduct/image";
import styles from "../../styles.module.scss";

const EditOrderPriceBreakUp = (props) => {
  const [modalShow, setModalShow] = useState(false);
  const {
    showEditOrderPriceBreakUp,
    setShowEditOrderPriceBreakUp,
    handleShowEditOrderPriceBreakUp,
    handleCloseEditOrderPriceBreakUp,
  } = props;

  return (
    <>
      <div className={'mb-4'}>
        <NewProgressBar />
      </div>
      <div className="mb-5">
        <Container fluid>
          <div className="px-3">
            <Row>
              <Col md={12} className="mb-4 mt-5">
                <div className="">
                  <div
                    role="button"
                    onClick={() => {
                      handleCloseEditOrderPriceBreakUp();
                    }}
                  >
                    <TitleHeader
                      title={"EDIT / VIEW PRICE UP"}
                      icon={profileIcon}
                    />
                  </div>
                </div>
              </Col>
            </Row>
          </div>
          <Form>
            <div className="mx-lg-5 mx-md-3">
              <Row>
                <Col md={12} className="mt-5">
                  <Row>
                    <Col
                      md={12}
                      sm={12}
                      className="d-flex justify-content-center mb-5"
                    >
                      <div className={`${styles.borderStyleNew}`}>
                        <Row>
                          <Col md={7}>
                            <div className="d-flex align-items-center justify-content-start mt-2 mx-3">
                              <div>
                                <Text
                                  size={15}
                                  fontWeight={700}
                                  color={colors?.black}
                                >
                                  Product Price Breakup
                                </Text>
                              </div>
                            </div>
                          </Col>
                          <Col md={5} className="d-flex">
                            <div>
                              <Image
                                src="/icons/dashboard/edit.svg"
                                width={10}
                                height={10}
                              />
                            </div>
                            <div className="ps-1">
                              <Text
                                size={13}
                                fontWeight={600}
                                color={colors?.golden}
                              >
                                Edit
                              </Text>
                            </div>
                          </Col>
                        </Row>
                        <Row>
                          <Col md={8}>
                            <div role="button" className={`my-1 py-2`}>
                              <Row>
                                <Col md={12}>
                                  <div className="newTable px-lg-4 px-md-4 px-sm-3  table-responsive">
                                    <Table>
                                      <thead>
                                        <tr>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Article{" "}
                                            </Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Weight{" "}
                                            </Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Today Rate{" "}
                                            </Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Disc Perc{" "}
                                            </Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Discount{" "}
                                            </Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Total Price{" "}
                                            </Text>
                                          </th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Gross Weight
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----- Gm
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Net Weight
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----- Gm
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ------ / Gm
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Diamond Weight
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----- Ct
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ------ / Ct
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Solitiare1
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Stones
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Making Charges
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Premium Price
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              GST
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Discount
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr className="border-bottom">
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Promo Code
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ------
                                            </Text>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </Table>
                                  </div>
                                </Col>
                              </Row>
                            </div>
                          </Col>
                          <Col md={4}></Col>
                        </Row>
                      </div>
                    </Col>
                  </Row>
                  <Row>
                    <Col
                      md={12}
                      sm={12}
                      className="d-flex justify-content-center mb-5"
                    >
                      <div className={`${styles.borderStyleNew}`}>
                        <Row>
                          <Col md={7}>
                            <div className="d-flex align-items-center justify-content-start mx-3 mt-2">
                              <div>
                                <Text
                                  size={15}
                                  fontWeight={700}
                                  color={colors?.black}
                                >
                                  Solitiare Details #1
                                </Text>
                              </div>
                            </div>
                          </Col>
                          <Col md={5} className="d-flex">
                            <div>
                              <Image
                                src="/icons/dashboard/edit.svg"
                                width={10}
                                height={10}
                              />
                            </div>
                            <div className="ps-1">
                              <Text
                                size={13}
                                fontWeight={600}
                                color={colors?.golden}
                              >
                                Edit
                              </Text>
                            </div>
                          </Col>
                        </Row>
                        <Row>
                          <Col md={8}>
                            <div className={`my-1 py-2`}>
                              <Row>
                                <Col md={12}>
                                  <div className="newTable px-lg-4 px-md-4 px-sm-3  table-responsive">
                                    <Table>
                                      <thead>
                                        <tr>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            ></Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            ></Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            ></Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Diam W8{" "}
                                            </Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Rate / Ct
                                            </Text>
                                          </th>
                                          <th>
                                            <Text
                                              size={13}
                                              fontWeight={800}
                                              color={colors?.black}
                                            >
                                              Total Price{" "}
                                            </Text>
                                          </th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Solitiare ID
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              :
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Solitiare Weight
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              :
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Solitiare Color
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              :
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Solitiare Clarity
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              :
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                        </tr>
                                        <tr className="border-bottom">
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={600}
                                              color={colors?.black}
                                            >
                                              Solitiare Cut
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            >
                                              :
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            >
                                              --%
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            >
                                              ----
                                            </Text>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            ></Text>
                                          </td>
                                          <td>
                                            <Text
                                              size={13}
                                              fontWeight={700}
                                              color={colors?.black}
                                            >
                                              -----
                                            </Text>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </Table>
                                  </div>
                                </Col>
                              </Row>
                            </div>
                          </Col>
                          <Col md={4}></Col>
                        </Row>
                      </div>
                    </Col>
                  </Row>
                </Col>
              </Row>
              <Row>
                <Col md={12} sm={12}>
                  <div className='p-5 center'><GradientBtn title='Submit' /></div>
                </Col>
              </Row>
            </div>
          </Form>
        </Container>
      </div>
    </>
  );
};

export default EditOrderPriceBreakUp;
